[ADD] financial indicators calculation
OCA/l10n-chile pull request #11
Opened 2019-10-22 18:54 UTC by Danisan

This module adds the option to update UF, UTM, USD, and EUR from SBIF (now called CMF.cl).

2019-10-22 19:08 UTC, max3903 commented
Aha :) #12

2019-10-22 19:35 UTC, max3903 commented
@Danisan Sabes donde esta la dependencia?

2019-10-22 20:20 UTC, Danisan commented
> @Danisan Sabes donde esta la dependencia?

Cual @max3903 ?

2019-10-22 20:42 UTC, Danisan commented
@max3903 the tests passed. Would you please test? Regarding the name... think is the same, but the module is already at odoo apps with this name. What do you suggest?

2019-10-22 20:45 UTC, max3903 commented
@Danisan

* I am talking about `webservices_generic`
* My suggestion would be to remove the module from the other repo and maintain it here collaboratively.
* You pushed your branch directly to the OCA repo. Can you push it to your account or organization?

2019-10-22 20:49 UTC, Danisan commented
> * webservices_generic

It is  [here](https://github.com/odoo-chile/webservices_generic), but in the new version there is no need of this. It was just to hold the connection parameters. In the new version it has been replaced by data in ir.config_parameter.

2019-10-22 21:22 UTC, max3903 commented on l10n_cl_financial_indicators/data/res.currency.csv
> +"base.UF","0.01","UF","after","UF","Unidad de Fomento"
```suggestion
"l10n_cl_financial_indicators.UF","0.01","UF","after","UF","Unidad de Fomento"
```

2019-10-22 21:22 UTC, max3903 commented on l10n_cl_financial_indicators/data/res.currency.csv
> +"base.UTM","0.01","UTM","after","UTM","UTM"
```suggestion
"l10n_cl_financial_indicators.UTM","0.01","UTM","after","UTM","UTM"
```

2019-10-22 21:23 UTC, max3903 commented on l10n_cl_financial_indicators/query0.sql
> +UPDATE decimal_precision set digits = 14 where name = 'Currency';
Missing newline.

2019-10-22 21:23 UTC, max3903 commented on l10n_cl_financial_indicators/query1.sql
> +UPDATE res_currency set rounding = 0.00000000000001 where name in ('UF', 'UTM');
Missing newline.

2019-10-22 21:36 UTC, Danisan commented on l10n_cl_financial_indicators/data/res.currency.csv
> +"base.UF","0.01","UF","after","UF","Unidad de Fomento"
same for UTM?

2019-10-22 21:39 UTC, Danisan commented on l10n_cl_financial_indicators/query1.sql
> +UPDATE res_currency set rounding = 0.00000000000001 where name in ('UF', 'UTM');
fixed in f9f031a9

2019-10-22 21:39 UTC, Danisan commented on l10n_cl_financial_indicators/query0.sql
> +UPDATE decimal_precision set digits = 14 where name = 'Currency';
fixed in f9f031a9

2019-10-23 00:22 UTC, max3903 requested changes
@Danisan Can you split the README.rst in a readme folder and add the `maintainers` and `development_status` keys in the manifest?

Ref: https://github.com/OCA/maintainer-tools/tree/master/template/module

2019-10-23 13:07 UTC, Danisan commented
> @Danisan
> 
> * I am talking about `webservices_generic`
> * My suggestion would be to remove the module from the other repo and maintain it here collaboratively.
> * You pushed your branch directly to the OCA repo. Can you push it to your account or organization?

OK @max3903 I will push from mine.

2019-10-23 13:09 UTC, Danisan commented
This thread will be closed then, to make the PR from our repo.

2019-10-23 13:09 UTC, closed without merging