[WIP]Electronic Billing with Xerox
OCA/l10n-chile pull request #59
Opened 2019-12-17 14:49 UTC by hpatelserpentcs

### Updated connector_acp
https://github.com/OCA/l10n-chile/issues/57

2019-12-17 15:00 UTC, max3903 commented on connector_acp/models/backend_acp.py
> +    type_of_connection = fields.Selection(
```suggestion
    connection_type = fields.Selection(
```

2019-12-17 15:33 UTC, dreispt commented on connector_acp/models/backend_acp.py
> +         ('wifi', 'WIFI')],
Make this an empty list for now.
If that error, then uase a single option `[('nd', 'Not defined')]`

2019-12-17 15:34 UTC, dreispt commented on connector_acp/models/etd_mixin.py
> +            kwargs.update({
I don't know it wasn't like that before: you can move this update into the `prepare_keywords()` method

2019-12-18 13:42 UTC, hpatelserpentcs commented
@dreispt 

updated above comment and now coming traceback is occurred when validating xml schemas.

2019-12-19 14:25 UTC, dreispt commented on connector_acp/data/document_data_view.xml
> +</odoo>
This is a new data file, it needs to be added to the manifest.
Please add it in the `demo` key.

2019-12-19 14:28 UTC, dreispt commented on connector_acp/models/etd_mixin.py
> +        filename = self.get_etd_filename(file)
Have this just `return` nothing.
Later modules will extend this to implement the Xerox specific logic.

2019-12-19 14:29 UTC, dreispt commented on connector_acp/models/etd_mixin.py
> -        """
Add optional argument files. 
If the filename generated for the current record exists in the files, the file template has the grouped flag set, then append content text to it.

2019-12-19 14:31 UTC, dreispt commented on connector_acp/models/etd_mixin.py
> +        files = []
```suggestion
        files = files or []
```

2019-12-19 14:38 UTC, dreispt commented on connector_acp/models/etd_mixin.py
> +            if file.file_type == 'txt':
```suggestion
            if file.grouped and filename in [f['name'] for f in files]:
                file_rec = [f for f in files if f['name'] == filename]
                if file_rec:
                    file_rec['content'] += res_content 
```

2019-12-19 14:42 UTC, dreispt requested changes
Some changes to make.

2019-12-24 07:06 UTC, closed without merging